// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_agent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_agent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_agent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_agent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_agent_2eproto;
namespace ai_agent {
class ResultCode;
class ResultCodeDefaultTypeInternal;
extern ResultCodeDefaultTypeInternal _ResultCode_default_instance_;
class ToolCallRequest;
class ToolCallRequestDefaultTypeInternal;
extern ToolCallRequestDefaultTypeInternal _ToolCallRequest_default_instance_;
class ToolCallResponse;
class ToolCallResponseDefaultTypeInternal;
extern ToolCallResponseDefaultTypeInternal _ToolCallResponse_default_instance_;
}  // namespace ai_agent
PROTOBUF_NAMESPACE_OPEN
template<> ::ai_agent::ResultCode* Arena::CreateMaybeMessage<::ai_agent::ResultCode>(Arena*);
template<> ::ai_agent::ToolCallRequest* Arena::CreateMaybeMessage<::ai_agent::ToolCallRequest>(Arena*);
template<> ::ai_agent::ToolCallResponse* Arena::CreateMaybeMessage<::ai_agent::ToolCallResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ai_agent {

// ===================================================================

class ResultCode :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ai_agent.ResultCode) */ {
 public:
  ResultCode();
  virtual ~ResultCode();

  ResultCode(const ResultCode& from);
  ResultCode(ResultCode&& from) noexcept
    : ResultCode() {
    *this = ::std::move(from);
  }

  inline ResultCode& operator=(const ResultCode& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResultCode& operator=(ResultCode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResultCode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResultCode* internal_default_instance() {
    return reinterpret_cast<const ResultCode*>(
               &_ResultCode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResultCode& a, ResultCode& b) {
    a.Swap(&b);
  }
  inline void Swap(ResultCode* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResultCode* New() const final {
    return CreateMaybeMessage<ResultCode>(nullptr);
  }

  ResultCode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResultCode>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResultCode& from);
  void MergeFrom(const ResultCode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResultCode* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ai_agent.ResultCode";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_agent_2eproto);
    return ::descriptor_table_agent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 2,
    kErrcodeFieldNumber = 1,
  };
  // bytes errmsg = 2;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const void* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int32 errcode = 1;
  void clear_errcode();
  ::PROTOBUF_NAMESPACE_ID::int32 errcode() const;
  void set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_errcode() const;
  void _internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ai_agent.ResultCode)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::PROTOBUF_NAMESPACE_ID::int32 errcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_agent_2eproto;
};
// -------------------------------------------------------------------

class ToolCallRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ai_agent.ToolCallRequest) */ {
 public:
  ToolCallRequest();
  virtual ~ToolCallRequest();

  ToolCallRequest(const ToolCallRequest& from);
  ToolCallRequest(ToolCallRequest&& from) noexcept
    : ToolCallRequest() {
    *this = ::std::move(from);
  }

  inline ToolCallRequest& operator=(const ToolCallRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ToolCallRequest& operator=(ToolCallRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ToolCallRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ToolCallRequest* internal_default_instance() {
    return reinterpret_cast<const ToolCallRequest*>(
               &_ToolCallRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ToolCallRequest& a, ToolCallRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ToolCallRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ToolCallRequest* New() const final {
    return CreateMaybeMessage<ToolCallRequest>(nullptr);
  }

  ToolCallRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ToolCallRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ToolCallRequest& from);
  void MergeFrom(const ToolCallRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ToolCallRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ai_agent.ToolCallRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_agent_2eproto);
    return ::descriptor_table_agent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTraceIdFieldNumber = 1,
    kToolNameFieldNumber = 2,
    kArgsJsonFieldNumber = 3,
  };
  // string trace_id = 1;
  void clear_trace_id();
  const std::string& trace_id() const;
  void set_trace_id(const std::string& value);
  void set_trace_id(std::string&& value);
  void set_trace_id(const char* value);
  void set_trace_id(const char* value, size_t size);
  std::string* mutable_trace_id();
  std::string* release_trace_id();
  void set_allocated_trace_id(std::string* trace_id);
  private:
  const std::string& _internal_trace_id() const;
  void _internal_set_trace_id(const std::string& value);
  std::string* _internal_mutable_trace_id();
  public:

  // string tool_name = 2;
  void clear_tool_name();
  const std::string& tool_name() const;
  void set_tool_name(const std::string& value);
  void set_tool_name(std::string&& value);
  void set_tool_name(const char* value);
  void set_tool_name(const char* value, size_t size);
  std::string* mutable_tool_name();
  std::string* release_tool_name();
  void set_allocated_tool_name(std::string* tool_name);
  private:
  const std::string& _internal_tool_name() const;
  void _internal_set_tool_name(const std::string& value);
  std::string* _internal_mutable_tool_name();
  public:

  // bytes args_json = 3;
  void clear_args_json();
  const std::string& args_json() const;
  void set_args_json(const std::string& value);
  void set_args_json(std::string&& value);
  void set_args_json(const char* value);
  void set_args_json(const void* value, size_t size);
  std::string* mutable_args_json();
  std::string* release_args_json();
  void set_allocated_args_json(std::string* args_json);
  private:
  const std::string& _internal_args_json() const;
  void _internal_set_args_json(const std::string& value);
  std::string* _internal_mutable_args_json();
  public:

  // @@protoc_insertion_point(class_scope:ai_agent.ToolCallRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tool_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr args_json_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_agent_2eproto;
};
// -------------------------------------------------------------------

class ToolCallResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ai_agent.ToolCallResponse) */ {
 public:
  ToolCallResponse();
  virtual ~ToolCallResponse();

  ToolCallResponse(const ToolCallResponse& from);
  ToolCallResponse(ToolCallResponse&& from) noexcept
    : ToolCallResponse() {
    *this = ::std::move(from);
  }

  inline ToolCallResponse& operator=(const ToolCallResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ToolCallResponse& operator=(ToolCallResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ToolCallResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ToolCallResponse* internal_default_instance() {
    return reinterpret_cast<const ToolCallResponse*>(
               &_ToolCallResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ToolCallResponse& a, ToolCallResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ToolCallResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ToolCallResponse* New() const final {
    return CreateMaybeMessage<ToolCallResponse>(nullptr);
  }

  ToolCallResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ToolCallResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ToolCallResponse& from);
  void MergeFrom(const ToolCallResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ToolCallResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ai_agent.ToolCallResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_agent_2eproto);
    return ::descriptor_table_agent_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOutputFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // bytes output = 2;
  void clear_output();
  const std::string& output() const;
  void set_output(const std::string& value);
  void set_output(std::string&& value);
  void set_output(const char* value);
  void set_output(const void* value, size_t size);
  std::string* mutable_output();
  std::string* release_output();
  void set_allocated_output(std::string* output);
  private:
  const std::string& _internal_output() const;
  void _internal_set_output(const std::string& value);
  std::string* _internal_mutable_output();
  public:

  // .ai_agent.ResultCode result = 1;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const ::ai_agent::ResultCode& result() const;
  ::ai_agent::ResultCode* release_result();
  ::ai_agent::ResultCode* mutable_result();
  void set_allocated_result(::ai_agent::ResultCode* result);
  private:
  const ::ai_agent::ResultCode& _internal_result() const;
  ::ai_agent::ResultCode* _internal_mutable_result();
  public:

  // @@protoc_insertion_point(class_scope:ai_agent.ToolCallResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_;
  ::ai_agent::ResultCode* result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_agent_2eproto;
};
// ===================================================================

class AgentServiceRpc_Stub;

class AgentServiceRpc : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline AgentServiceRpc() {};
 public:
  virtual ~AgentServiceRpc();

  typedef AgentServiceRpc_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void Execute(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::ai_agent::ToolCallRequest* request,
                       ::ai_agent::ToolCallResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(AgentServiceRpc);
};

class AgentServiceRpc_Stub : public AgentServiceRpc {
 public:
  AgentServiceRpc_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  AgentServiceRpc_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~AgentServiceRpc_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements AgentServiceRpc ------------------------------------------

  void Execute(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::ai_agent::ToolCallRequest* request,
                       ::ai_agent::ToolCallResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(AgentServiceRpc_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResultCode

// int32 errcode = 1;
inline void ResultCode::clear_errcode() {
  errcode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResultCode::_internal_errcode() const {
  return errcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ResultCode::errcode() const {
  // @@protoc_insertion_point(field_get:ai_agent.ResultCode.errcode)
  return _internal_errcode();
}
inline void ResultCode::_internal_set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  errcode_ = value;
}
inline void ResultCode::set_errcode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:ai_agent.ResultCode.errcode)
}

// bytes errmsg = 2;
inline void ResultCode::clear_errmsg() {
  errmsg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ResultCode::errmsg() const {
  // @@protoc_insertion_point(field_get:ai_agent.ResultCode.errmsg)
  return _internal_errmsg();
}
inline void ResultCode::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:ai_agent.ResultCode.errmsg)
}
inline std::string* ResultCode::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:ai_agent.ResultCode.errmsg)
  return _internal_mutable_errmsg();
}
inline const std::string& ResultCode::_internal_errmsg() const {
  return errmsg_.GetNoArena();
}
inline void ResultCode::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ResultCode::set_errmsg(std::string&& value) {
  
  errmsg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ai_agent.ResultCode.errmsg)
}
inline void ResultCode::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ai_agent.ResultCode.errmsg)
}
inline void ResultCode::set_errmsg(const void* value, size_t size) {
  
  errmsg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ai_agent.ResultCode.errmsg)
}
inline std::string* ResultCode::_internal_mutable_errmsg() {
  
  return errmsg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ResultCode::release_errmsg() {
  // @@protoc_insertion_point(field_release:ai_agent.ResultCode.errmsg)
  
  return errmsg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ResultCode::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg);
  // @@protoc_insertion_point(field_set_allocated:ai_agent.ResultCode.errmsg)
}

// -------------------------------------------------------------------

// ToolCallRequest

// string trace_id = 1;
inline void ToolCallRequest::clear_trace_id() {
  trace_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ToolCallRequest::trace_id() const {
  // @@protoc_insertion_point(field_get:ai_agent.ToolCallRequest.trace_id)
  return _internal_trace_id();
}
inline void ToolCallRequest::set_trace_id(const std::string& value) {
  _internal_set_trace_id(value);
  // @@protoc_insertion_point(field_set:ai_agent.ToolCallRequest.trace_id)
}
inline std::string* ToolCallRequest::mutable_trace_id() {
  // @@protoc_insertion_point(field_mutable:ai_agent.ToolCallRequest.trace_id)
  return _internal_mutable_trace_id();
}
inline const std::string& ToolCallRequest::_internal_trace_id() const {
  return trace_id_.GetNoArena();
}
inline void ToolCallRequest::_internal_set_trace_id(const std::string& value) {
  
  trace_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ToolCallRequest::set_trace_id(std::string&& value) {
  
  trace_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ai_agent.ToolCallRequest.trace_id)
}
inline void ToolCallRequest::set_trace_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trace_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ai_agent.ToolCallRequest.trace_id)
}
inline void ToolCallRequest::set_trace_id(const char* value, size_t size) {
  
  trace_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ai_agent.ToolCallRequest.trace_id)
}
inline std::string* ToolCallRequest::_internal_mutable_trace_id() {
  
  return trace_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ToolCallRequest::release_trace_id() {
  // @@protoc_insertion_point(field_release:ai_agent.ToolCallRequest.trace_id)
  
  return trace_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ToolCallRequest::set_allocated_trace_id(std::string* trace_id) {
  if (trace_id != nullptr) {
    
  } else {
    
  }
  trace_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trace_id);
  // @@protoc_insertion_point(field_set_allocated:ai_agent.ToolCallRequest.trace_id)
}

// string tool_name = 2;
inline void ToolCallRequest::clear_tool_name() {
  tool_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ToolCallRequest::tool_name() const {
  // @@protoc_insertion_point(field_get:ai_agent.ToolCallRequest.tool_name)
  return _internal_tool_name();
}
inline void ToolCallRequest::set_tool_name(const std::string& value) {
  _internal_set_tool_name(value);
  // @@protoc_insertion_point(field_set:ai_agent.ToolCallRequest.tool_name)
}
inline std::string* ToolCallRequest::mutable_tool_name() {
  // @@protoc_insertion_point(field_mutable:ai_agent.ToolCallRequest.tool_name)
  return _internal_mutable_tool_name();
}
inline const std::string& ToolCallRequest::_internal_tool_name() const {
  return tool_name_.GetNoArena();
}
inline void ToolCallRequest::_internal_set_tool_name(const std::string& value) {
  
  tool_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ToolCallRequest::set_tool_name(std::string&& value) {
  
  tool_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ai_agent.ToolCallRequest.tool_name)
}
inline void ToolCallRequest::set_tool_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tool_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ai_agent.ToolCallRequest.tool_name)
}
inline void ToolCallRequest::set_tool_name(const char* value, size_t size) {
  
  tool_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ai_agent.ToolCallRequest.tool_name)
}
inline std::string* ToolCallRequest::_internal_mutable_tool_name() {
  
  return tool_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ToolCallRequest::release_tool_name() {
  // @@protoc_insertion_point(field_release:ai_agent.ToolCallRequest.tool_name)
  
  return tool_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ToolCallRequest::set_allocated_tool_name(std::string* tool_name) {
  if (tool_name != nullptr) {
    
  } else {
    
  }
  tool_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tool_name);
  // @@protoc_insertion_point(field_set_allocated:ai_agent.ToolCallRequest.tool_name)
}

// bytes args_json = 3;
inline void ToolCallRequest::clear_args_json() {
  args_json_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ToolCallRequest::args_json() const {
  // @@protoc_insertion_point(field_get:ai_agent.ToolCallRequest.args_json)
  return _internal_args_json();
}
inline void ToolCallRequest::set_args_json(const std::string& value) {
  _internal_set_args_json(value);
  // @@protoc_insertion_point(field_set:ai_agent.ToolCallRequest.args_json)
}
inline std::string* ToolCallRequest::mutable_args_json() {
  // @@protoc_insertion_point(field_mutable:ai_agent.ToolCallRequest.args_json)
  return _internal_mutable_args_json();
}
inline const std::string& ToolCallRequest::_internal_args_json() const {
  return args_json_.GetNoArena();
}
inline void ToolCallRequest::_internal_set_args_json(const std::string& value) {
  
  args_json_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ToolCallRequest::set_args_json(std::string&& value) {
  
  args_json_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ai_agent.ToolCallRequest.args_json)
}
inline void ToolCallRequest::set_args_json(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  args_json_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ai_agent.ToolCallRequest.args_json)
}
inline void ToolCallRequest::set_args_json(const void* value, size_t size) {
  
  args_json_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ai_agent.ToolCallRequest.args_json)
}
inline std::string* ToolCallRequest::_internal_mutable_args_json() {
  
  return args_json_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ToolCallRequest::release_args_json() {
  // @@protoc_insertion_point(field_release:ai_agent.ToolCallRequest.args_json)
  
  return args_json_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ToolCallRequest::set_allocated_args_json(std::string* args_json) {
  if (args_json != nullptr) {
    
  } else {
    
  }
  args_json_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), args_json);
  // @@protoc_insertion_point(field_set_allocated:ai_agent.ToolCallRequest.args_json)
}

// -------------------------------------------------------------------

// ToolCallResponse

// .ai_agent.ResultCode result = 1;
inline bool ToolCallResponse::_internal_has_result() const {
  return this != internal_default_instance() && result_ != nullptr;
}
inline bool ToolCallResponse::has_result() const {
  return _internal_has_result();
}
inline void ToolCallResponse::clear_result() {
  if (GetArenaNoVirtual() == nullptr && result_ != nullptr) {
    delete result_;
  }
  result_ = nullptr;
}
inline const ::ai_agent::ResultCode& ToolCallResponse::_internal_result() const {
  const ::ai_agent::ResultCode* p = result_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ai_agent::ResultCode*>(
      &::ai_agent::_ResultCode_default_instance_);
}
inline const ::ai_agent::ResultCode& ToolCallResponse::result() const {
  // @@protoc_insertion_point(field_get:ai_agent.ToolCallResponse.result)
  return _internal_result();
}
inline ::ai_agent::ResultCode* ToolCallResponse::release_result() {
  // @@protoc_insertion_point(field_release:ai_agent.ToolCallResponse.result)
  
  ::ai_agent::ResultCode* temp = result_;
  result_ = nullptr;
  return temp;
}
inline ::ai_agent::ResultCode* ToolCallResponse::_internal_mutable_result() {
  
  if (result_ == nullptr) {
    auto* p = CreateMaybeMessage<::ai_agent::ResultCode>(GetArenaNoVirtual());
    result_ = p;
  }
  return result_;
}
inline ::ai_agent::ResultCode* ToolCallResponse::mutable_result() {
  // @@protoc_insertion_point(field_mutable:ai_agent.ToolCallResponse.result)
  return _internal_mutable_result();
}
inline void ToolCallResponse::set_allocated_result(::ai_agent::ResultCode* result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete result_;
  }
  if (result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, result, submessage_arena);
    }
    
  } else {
    
  }
  result_ = result;
  // @@protoc_insertion_point(field_set_allocated:ai_agent.ToolCallResponse.result)
}

// bytes output = 2;
inline void ToolCallResponse::clear_output() {
  output_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ToolCallResponse::output() const {
  // @@protoc_insertion_point(field_get:ai_agent.ToolCallResponse.output)
  return _internal_output();
}
inline void ToolCallResponse::set_output(const std::string& value) {
  _internal_set_output(value);
  // @@protoc_insertion_point(field_set:ai_agent.ToolCallResponse.output)
}
inline std::string* ToolCallResponse::mutable_output() {
  // @@protoc_insertion_point(field_mutable:ai_agent.ToolCallResponse.output)
  return _internal_mutable_output();
}
inline const std::string& ToolCallResponse::_internal_output() const {
  return output_.GetNoArena();
}
inline void ToolCallResponse::_internal_set_output(const std::string& value) {
  
  output_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ToolCallResponse::set_output(std::string&& value) {
  
  output_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ai_agent.ToolCallResponse.output)
}
inline void ToolCallResponse::set_output(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  output_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ai_agent.ToolCallResponse.output)
}
inline void ToolCallResponse::set_output(const void* value, size_t size) {
  
  output_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ai_agent.ToolCallResponse.output)
}
inline std::string* ToolCallResponse::_internal_mutable_output() {
  
  return output_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ToolCallResponse::release_output() {
  // @@protoc_insertion_point(field_release:ai_agent.ToolCallResponse.output)
  
  return output_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ToolCallResponse::set_allocated_output(std::string* output) {
  if (output != nullptr) {
    
  } else {
    
  }
  output_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output);
  // @@protoc_insertion_point(field_set_allocated:ai_agent.ToolCallResponse.output)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ai_agent

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_agent_2eproto
