version: '3.3'

networks:
  agent_net:
    driver: bridge

services:
  # ==========================================
  # 1. 存储与发现层
  # ==========================================
  zookeeper:
    image: zookeeper:3.8
    container_name: mprpc-zookeeper-agent
    networks:
      - agent_net
    ports:
      - "2181:2181"

  mysql:
    image: mysql:8.0
    container_name: mprpc-mysql-agent
    networks:
      - agent_net
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=chat
    ports:
      - "3307:3306" # 宿主机用3307连，容器内部依然是3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p123456"]
      timeout: 20s
      retries: 10

  # ==========================================
  # 2. 监控观测层
  # ==========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: mprpc-prometheus-agent
    networks:
      - agent_net
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090" # 避开旧的 9091/9090

  grafana:
    image: grafana/grafana:latest
    container_name: mprpc-grafana-agent
    networks:
      - agent_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3002:3000" # 避开旧的 3001/3000
    depends_on:
      - prometheus

  # ==========================================
  # 3. 分布式 Agent 业务层
  # ==========================================
  gateway:
    image: lele-rpc-agent:v1
    container_name: agent-gateway-agent
    volumes:
      # 宿主机路径 : 容器内程序预期的路径
      - ./bin/knowledge.txt:/app/knowledge.txt 
      - ./bin/gateway.conf:/app/gateway.conf
      - ./prompts:/app/prompts
    networks:
      - agent_net
    ports:
      - "5556:5556"
      - "8081:8081"
    depends_on:
      - zookeeper
    command: ["./agent_gateway", "-i", "gateway.conf"]
    environment:                 # 👈 注意这里的缩进
      - zookeeperip=zookeeper    # Docker 内部用域名
      - db_ip=mysql              # Docker 内部用服务名
      - db_port=3306             # 容器内部直连 MySQL 默认端口

  provider:
    image: lele-rpc-agent:v1
    container_name: agent-provider-agent
    networks:
      - agent_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      - mysql
    environment:                 # 👈 核心：给 Provider 也打上“环境装甲”
      - zookeeperip=zookeeper    # 强行覆盖 test_8001.conf 里的 127.0.0.1
      - db_ip=mysql
      - db_port=3306             # 同样，容器内互访用 3306
    command: ["./agent_provider", "-i", "test_8001.conf"]

  redis:
    image: redis:latest
    container_name: mprpc-redis
    networks:
      - agent_net  # 确保这个网络和你现有的容器在同一个网段
    ports:
      - "6379:6379"