// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mcp.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mcp_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mcp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mcp_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mcp_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mcp_2eproto;
namespace mcp {
class CallToolRequest;
class CallToolRequestDefaultTypeInternal;
extern CallToolRequestDefaultTypeInternal _CallToolRequest_default_instance_;
class CallToolResponse;
class CallToolResponseDefaultTypeInternal;
extern CallToolResponseDefaultTypeInternal _CallToolResponse_default_instance_;
class ListToolsRequest;
class ListToolsRequestDefaultTypeInternal;
extern ListToolsRequestDefaultTypeInternal _ListToolsRequest_default_instance_;
class ListToolsResponse;
class ListToolsResponseDefaultTypeInternal;
extern ListToolsResponseDefaultTypeInternal _ListToolsResponse_default_instance_;
class Tool;
class ToolDefaultTypeInternal;
extern ToolDefaultTypeInternal _Tool_default_instance_;
}  // namespace mcp
PROTOBUF_NAMESPACE_OPEN
template<> ::mcp::CallToolRequest* Arena::CreateMaybeMessage<::mcp::CallToolRequest>(Arena*);
template<> ::mcp::CallToolResponse* Arena::CreateMaybeMessage<::mcp::CallToolResponse>(Arena*);
template<> ::mcp::ListToolsRequest* Arena::CreateMaybeMessage<::mcp::ListToolsRequest>(Arena*);
template<> ::mcp::ListToolsResponse* Arena::CreateMaybeMessage<::mcp::ListToolsResponse>(Arena*);
template<> ::mcp::Tool* Arena::CreateMaybeMessage<::mcp::Tool>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mcp {

// ===================================================================

class Tool :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mcp.Tool) */ {
 public:
  Tool();
  virtual ~Tool();

  Tool(const Tool& from);
  Tool(Tool&& from) noexcept
    : Tool() {
    *this = ::std::move(from);
  }

  inline Tool& operator=(const Tool& from) {
    CopyFrom(from);
    return *this;
  }
  inline Tool& operator=(Tool&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Tool& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Tool* internal_default_instance() {
    return reinterpret_cast<const Tool*>(
               &_Tool_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Tool& a, Tool& b) {
    a.Swap(&b);
  }
  inline void Swap(Tool* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Tool* New() const final {
    return CreateMaybeMessage<Tool>(nullptr);
  }

  Tool* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Tool>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Tool& from);
  void MergeFrom(const Tool& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Tool* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mcp.Tool";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mcp_2eproto);
    return ::descriptor_table_mcp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kDescriptionFieldNumber = 2,
    kInputSchemaFieldNumber = 3,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string description = 2;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // string input_schema = 3;
  void clear_input_schema();
  const std::string& input_schema() const;
  void set_input_schema(const std::string& value);
  void set_input_schema(std::string&& value);
  void set_input_schema(const char* value);
  void set_input_schema(const char* value, size_t size);
  std::string* mutable_input_schema();
  std::string* release_input_schema();
  void set_allocated_input_schema(std::string* input_schema);
  private:
  const std::string& _internal_input_schema() const;
  void _internal_set_input_schema(const std::string& value);
  std::string* _internal_mutable_input_schema();
  public:

  // @@protoc_insertion_point(class_scope:mcp.Tool)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr input_schema_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mcp_2eproto;
};
// -------------------------------------------------------------------

class ListToolsRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mcp.ListToolsRequest) */ {
 public:
  ListToolsRequest();
  virtual ~ListToolsRequest();

  ListToolsRequest(const ListToolsRequest& from);
  ListToolsRequest(ListToolsRequest&& from) noexcept
    : ListToolsRequest() {
    *this = ::std::move(from);
  }

  inline ListToolsRequest& operator=(const ListToolsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListToolsRequest& operator=(ListToolsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ListToolsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListToolsRequest* internal_default_instance() {
    return reinterpret_cast<const ListToolsRequest*>(
               &_ListToolsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ListToolsRequest& a, ListToolsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ListToolsRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ListToolsRequest* New() const final {
    return CreateMaybeMessage<ListToolsRequest>(nullptr);
  }

  ListToolsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ListToolsRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ListToolsRequest& from);
  void MergeFrom(const ListToolsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListToolsRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mcp.ListToolsRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mcp_2eproto);
    return ::descriptor_table_mcp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mcp.ListToolsRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mcp_2eproto;
};
// -------------------------------------------------------------------

class ListToolsResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mcp.ListToolsResponse) */ {
 public:
  ListToolsResponse();
  virtual ~ListToolsResponse();

  ListToolsResponse(const ListToolsResponse& from);
  ListToolsResponse(ListToolsResponse&& from) noexcept
    : ListToolsResponse() {
    *this = ::std::move(from);
  }

  inline ListToolsResponse& operator=(const ListToolsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListToolsResponse& operator=(ListToolsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ListToolsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListToolsResponse* internal_default_instance() {
    return reinterpret_cast<const ListToolsResponse*>(
               &_ListToolsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ListToolsResponse& a, ListToolsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ListToolsResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ListToolsResponse* New() const final {
    return CreateMaybeMessage<ListToolsResponse>(nullptr);
  }

  ListToolsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ListToolsResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ListToolsResponse& from);
  void MergeFrom(const ListToolsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListToolsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mcp.ListToolsResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mcp_2eproto);
    return ::descriptor_table_mcp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kToolsFieldNumber = 1,
  };
  // repeated .mcp.Tool tools = 1;
  int tools_size() const;
  private:
  int _internal_tools_size() const;
  public:
  void clear_tools();
  ::mcp::Tool* mutable_tools(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mcp::Tool >*
      mutable_tools();
  private:
  const ::mcp::Tool& _internal_tools(int index) const;
  ::mcp::Tool* _internal_add_tools();
  public:
  const ::mcp::Tool& tools(int index) const;
  ::mcp::Tool* add_tools();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mcp::Tool >&
      tools() const;

  // @@protoc_insertion_point(class_scope:mcp.ListToolsResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mcp::Tool > tools_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mcp_2eproto;
};
// -------------------------------------------------------------------

class CallToolRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mcp.CallToolRequest) */ {
 public:
  CallToolRequest();
  virtual ~CallToolRequest();

  CallToolRequest(const CallToolRequest& from);
  CallToolRequest(CallToolRequest&& from) noexcept
    : CallToolRequest() {
    *this = ::std::move(from);
  }

  inline CallToolRequest& operator=(const CallToolRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallToolRequest& operator=(CallToolRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CallToolRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CallToolRequest* internal_default_instance() {
    return reinterpret_cast<const CallToolRequest*>(
               &_CallToolRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CallToolRequest& a, CallToolRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CallToolRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CallToolRequest* New() const final {
    return CreateMaybeMessage<CallToolRequest>(nullptr);
  }

  CallToolRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CallToolRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CallToolRequest& from);
  void MergeFrom(const CallToolRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CallToolRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mcp.CallToolRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mcp_2eproto);
    return ::descriptor_table_mcp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kArgumentsFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string arguments = 2;
  void clear_arguments();
  const std::string& arguments() const;
  void set_arguments(const std::string& value);
  void set_arguments(std::string&& value);
  void set_arguments(const char* value);
  void set_arguments(const char* value, size_t size);
  std::string* mutable_arguments();
  std::string* release_arguments();
  void set_allocated_arguments(std::string* arguments);
  private:
  const std::string& _internal_arguments() const;
  void _internal_set_arguments(const std::string& value);
  std::string* _internal_mutable_arguments();
  public:

  // @@protoc_insertion_point(class_scope:mcp.CallToolRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr arguments_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mcp_2eproto;
};
// -------------------------------------------------------------------

class CallToolResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mcp.CallToolResponse) */ {
 public:
  CallToolResponse();
  virtual ~CallToolResponse();

  CallToolResponse(const CallToolResponse& from);
  CallToolResponse(CallToolResponse&& from) noexcept
    : CallToolResponse() {
    *this = ::std::move(from);
  }

  inline CallToolResponse& operator=(const CallToolResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallToolResponse& operator=(CallToolResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CallToolResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CallToolResponse* internal_default_instance() {
    return reinterpret_cast<const CallToolResponse*>(
               &_CallToolResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CallToolResponse& a, CallToolResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CallToolResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CallToolResponse* New() const final {
    return CreateMaybeMessage<CallToolResponse>(nullptr);
  }

  CallToolResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CallToolResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CallToolResponse& from);
  void MergeFrom(const CallToolResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CallToolResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mcp.CallToolResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mcp_2eproto);
    return ::descriptor_table_mcp_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 2,
    kIsErrorFieldNumber = 1,
  };
  // string content = 2;
  void clear_content();
  const std::string& content() const;
  void set_content(const std::string& value);
  void set_content(std::string&& value);
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  std::string* mutable_content();
  std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // bool is_error = 1;
  void clear_is_error();
  bool is_error() const;
  void set_is_error(bool value);
  private:
  bool _internal_is_error() const;
  void _internal_set_is_error(bool value);
  public:

  // @@protoc_insertion_point(class_scope:mcp.CallToolResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  bool is_error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mcp_2eproto;
};
// ===================================================================

class McpToolService_Stub;

class McpToolService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline McpToolService() {};
 public:
  virtual ~McpToolService();

  typedef McpToolService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void ListTools(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mcp::ListToolsRequest* request,
                       ::mcp::ListToolsResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void CallTool(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mcp::CallToolRequest* request,
                       ::mcp::CallToolResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(McpToolService);
};

class McpToolService_Stub : public McpToolService {
 public:
  McpToolService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  McpToolService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~McpToolService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements McpToolService ------------------------------------------

  void ListTools(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mcp::ListToolsRequest* request,
                       ::mcp::ListToolsResponse* response,
                       ::google::protobuf::Closure* done);
  void CallTool(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::mcp::CallToolRequest* request,
                       ::mcp::CallToolResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(McpToolService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Tool

// string name = 1;
inline void Tool::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Tool::name() const {
  // @@protoc_insertion_point(field_get:mcp.Tool.name)
  return _internal_name();
}
inline void Tool::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:mcp.Tool.name)
}
inline std::string* Tool::mutable_name() {
  // @@protoc_insertion_point(field_mutable:mcp.Tool.name)
  return _internal_mutable_name();
}
inline const std::string& Tool::_internal_name() const {
  return name_.GetNoArena();
}
inline void Tool::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Tool::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mcp.Tool.name)
}
inline void Tool::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mcp.Tool.name)
}
inline void Tool::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mcp.Tool.name)
}
inline std::string* Tool::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Tool::release_name() {
  // @@protoc_insertion_point(field_release:mcp.Tool.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Tool::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mcp.Tool.name)
}

// string description = 2;
inline void Tool::clear_description() {
  description_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Tool::description() const {
  // @@protoc_insertion_point(field_get:mcp.Tool.description)
  return _internal_description();
}
inline void Tool::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:mcp.Tool.description)
}
inline std::string* Tool::mutable_description() {
  // @@protoc_insertion_point(field_mutable:mcp.Tool.description)
  return _internal_mutable_description();
}
inline const std::string& Tool::_internal_description() const {
  return description_.GetNoArena();
}
inline void Tool::_internal_set_description(const std::string& value) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Tool::set_description(std::string&& value) {
  
  description_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mcp.Tool.description)
}
inline void Tool::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mcp.Tool.description)
}
inline void Tool::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mcp.Tool.description)
}
inline std::string* Tool::_internal_mutable_description() {
  
  return description_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Tool::release_description() {
  // @@protoc_insertion_point(field_release:mcp.Tool.description)
  
  return description_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Tool::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:mcp.Tool.description)
}

// string input_schema = 3;
inline void Tool::clear_input_schema() {
  input_schema_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Tool::input_schema() const {
  // @@protoc_insertion_point(field_get:mcp.Tool.input_schema)
  return _internal_input_schema();
}
inline void Tool::set_input_schema(const std::string& value) {
  _internal_set_input_schema(value);
  // @@protoc_insertion_point(field_set:mcp.Tool.input_schema)
}
inline std::string* Tool::mutable_input_schema() {
  // @@protoc_insertion_point(field_mutable:mcp.Tool.input_schema)
  return _internal_mutable_input_schema();
}
inline const std::string& Tool::_internal_input_schema() const {
  return input_schema_.GetNoArena();
}
inline void Tool::_internal_set_input_schema(const std::string& value) {
  
  input_schema_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Tool::set_input_schema(std::string&& value) {
  
  input_schema_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mcp.Tool.input_schema)
}
inline void Tool::set_input_schema(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  input_schema_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mcp.Tool.input_schema)
}
inline void Tool::set_input_schema(const char* value, size_t size) {
  
  input_schema_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mcp.Tool.input_schema)
}
inline std::string* Tool::_internal_mutable_input_schema() {
  
  return input_schema_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Tool::release_input_schema() {
  // @@protoc_insertion_point(field_release:mcp.Tool.input_schema)
  
  return input_schema_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Tool::set_allocated_input_schema(std::string* input_schema) {
  if (input_schema != nullptr) {
    
  } else {
    
  }
  input_schema_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), input_schema);
  // @@protoc_insertion_point(field_set_allocated:mcp.Tool.input_schema)
}

// -------------------------------------------------------------------

// ListToolsRequest

// -------------------------------------------------------------------

// ListToolsResponse

// repeated .mcp.Tool tools = 1;
inline int ListToolsResponse::_internal_tools_size() const {
  return tools_.size();
}
inline int ListToolsResponse::tools_size() const {
  return _internal_tools_size();
}
inline void ListToolsResponse::clear_tools() {
  tools_.Clear();
}
inline ::mcp::Tool* ListToolsResponse::mutable_tools(int index) {
  // @@protoc_insertion_point(field_mutable:mcp.ListToolsResponse.tools)
  return tools_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mcp::Tool >*
ListToolsResponse::mutable_tools() {
  // @@protoc_insertion_point(field_mutable_list:mcp.ListToolsResponse.tools)
  return &tools_;
}
inline const ::mcp::Tool& ListToolsResponse::_internal_tools(int index) const {
  return tools_.Get(index);
}
inline const ::mcp::Tool& ListToolsResponse::tools(int index) const {
  // @@protoc_insertion_point(field_get:mcp.ListToolsResponse.tools)
  return _internal_tools(index);
}
inline ::mcp::Tool* ListToolsResponse::_internal_add_tools() {
  return tools_.Add();
}
inline ::mcp::Tool* ListToolsResponse::add_tools() {
  // @@protoc_insertion_point(field_add:mcp.ListToolsResponse.tools)
  return _internal_add_tools();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::mcp::Tool >&
ListToolsResponse::tools() const {
  // @@protoc_insertion_point(field_list:mcp.ListToolsResponse.tools)
  return tools_;
}

// -------------------------------------------------------------------

// CallToolRequest

// string name = 1;
inline void CallToolRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CallToolRequest::name() const {
  // @@protoc_insertion_point(field_get:mcp.CallToolRequest.name)
  return _internal_name();
}
inline void CallToolRequest::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:mcp.CallToolRequest.name)
}
inline std::string* CallToolRequest::mutable_name() {
  // @@protoc_insertion_point(field_mutable:mcp.CallToolRequest.name)
  return _internal_mutable_name();
}
inline const std::string& CallToolRequest::_internal_name() const {
  return name_.GetNoArena();
}
inline void CallToolRequest::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CallToolRequest::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mcp.CallToolRequest.name)
}
inline void CallToolRequest::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mcp.CallToolRequest.name)
}
inline void CallToolRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mcp.CallToolRequest.name)
}
inline std::string* CallToolRequest::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CallToolRequest::release_name() {
  // @@protoc_insertion_point(field_release:mcp.CallToolRequest.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CallToolRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mcp.CallToolRequest.name)
}

// string arguments = 2;
inline void CallToolRequest::clear_arguments() {
  arguments_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CallToolRequest::arguments() const {
  // @@protoc_insertion_point(field_get:mcp.CallToolRequest.arguments)
  return _internal_arguments();
}
inline void CallToolRequest::set_arguments(const std::string& value) {
  _internal_set_arguments(value);
  // @@protoc_insertion_point(field_set:mcp.CallToolRequest.arguments)
}
inline std::string* CallToolRequest::mutable_arguments() {
  // @@protoc_insertion_point(field_mutable:mcp.CallToolRequest.arguments)
  return _internal_mutable_arguments();
}
inline const std::string& CallToolRequest::_internal_arguments() const {
  return arguments_.GetNoArena();
}
inline void CallToolRequest::_internal_set_arguments(const std::string& value) {
  
  arguments_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CallToolRequest::set_arguments(std::string&& value) {
  
  arguments_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mcp.CallToolRequest.arguments)
}
inline void CallToolRequest::set_arguments(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  arguments_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mcp.CallToolRequest.arguments)
}
inline void CallToolRequest::set_arguments(const char* value, size_t size) {
  
  arguments_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mcp.CallToolRequest.arguments)
}
inline std::string* CallToolRequest::_internal_mutable_arguments() {
  
  return arguments_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CallToolRequest::release_arguments() {
  // @@protoc_insertion_point(field_release:mcp.CallToolRequest.arguments)
  
  return arguments_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CallToolRequest::set_allocated_arguments(std::string* arguments) {
  if (arguments != nullptr) {
    
  } else {
    
  }
  arguments_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), arguments);
  // @@protoc_insertion_point(field_set_allocated:mcp.CallToolRequest.arguments)
}

// -------------------------------------------------------------------

// CallToolResponse

// bool is_error = 1;
inline void CallToolResponse::clear_is_error() {
  is_error_ = false;
}
inline bool CallToolResponse::_internal_is_error() const {
  return is_error_;
}
inline bool CallToolResponse::is_error() const {
  // @@protoc_insertion_point(field_get:mcp.CallToolResponse.is_error)
  return _internal_is_error();
}
inline void CallToolResponse::_internal_set_is_error(bool value) {
  
  is_error_ = value;
}
inline void CallToolResponse::set_is_error(bool value) {
  _internal_set_is_error(value);
  // @@protoc_insertion_point(field_set:mcp.CallToolResponse.is_error)
}

// string content = 2;
inline void CallToolResponse::clear_content() {
  content_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CallToolResponse::content() const {
  // @@protoc_insertion_point(field_get:mcp.CallToolResponse.content)
  return _internal_content();
}
inline void CallToolResponse::set_content(const std::string& value) {
  _internal_set_content(value);
  // @@protoc_insertion_point(field_set:mcp.CallToolResponse.content)
}
inline std::string* CallToolResponse::mutable_content() {
  // @@protoc_insertion_point(field_mutable:mcp.CallToolResponse.content)
  return _internal_mutable_content();
}
inline const std::string& CallToolResponse::_internal_content() const {
  return content_.GetNoArena();
}
inline void CallToolResponse::_internal_set_content(const std::string& value) {
  
  content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CallToolResponse::set_content(std::string&& value) {
  
  content_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mcp.CallToolResponse.content)
}
inline void CallToolResponse::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mcp.CallToolResponse.content)
}
inline void CallToolResponse::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mcp.CallToolResponse.content)
}
inline std::string* CallToolResponse::_internal_mutable_content() {
  
  return content_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CallToolResponse::release_content() {
  // @@protoc_insertion_point(field_release:mcp.CallToolResponse.content)
  
  return content_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CallToolResponse::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:mcp.CallToolResponse.content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mcp

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mcp_2eproto
